# Generated by Django 6.0.1 on 2026-03-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Gym Owner',
                'db_table': 'owners_owner',
            },
        ),
    ]
