# Generated by Django 6.0.1 on 2026-03-30 05:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('GOOGLE', 'Google'), ('APPLE', 'Apple'), ('FACEBOOK', 'Facebook')], max_length=50)),
                ('provider_uid', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_auths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'provider_uid'], name='users_socia_provide_57d690_idx')],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
