# Generated by Django 6.0.1 on 2026-02-05 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(auto_now_add=True)),
                ('entry_source', models.CharField(default='QR_SCAN', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='gymmember',
            name='core_gymmem_extra_i_8209fc_gin',
        ),
        migrations.AddField(
            model_name='gymattendance',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gymattends', to='core.gym'),
        ),
        migrations.AddField(
            model_name='gymattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memattends', to='core.gymmember'),
        ),
        migrations.AddConstraint(
            model_name='gymattendance',
            constraint=models.UniqueConstraint(fields=('gym', 'member', 'date'), name='unique_daily_attendance'),
        ),
    ]
