# Generated by Django 6.0.1 on 2026-03-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to='owners.owner'),
        ),
        migrations.AddField(
            model_name='gymattendance',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gymattends', to='core.gym'),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.gym'),
        ),
    ]
