# Generated by Django 6.0.1 on 2026-03-22 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmember',
            name='user',
            field=models.OneToOneField(help_text='The global identity associated with this gym membership.', on_delete=django.db.models.deletion.CASCADE, related_name='gym_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memattends', to='core.gymmember'),
        ),
        migrations.AddField(
            model_name='gymmemberfieldschema',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_field_schema', to='core.gym'),
        ),
        migrations.AddIndex(
            model_name='gymmember',
            index=models.Index(fields=['membership_end'], name='core_gymmem_members_40420c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gymmember',
            unique_together={('user', 'gym')},
        ),
        migrations.AddIndex(
            model_name='gymattendance',
            index=models.Index(fields=['gym', 'member', 'date'], name='core_gymatt_gym_id_bc7fc1_idx'),
        ),
        migrations.AddConstraint(
            model_name='gymattendance',
            constraint=models.UniqueConstraint(fields=('gym', 'member', 'date'), name='unique_daily_attendance'),
        ),
        migrations.AlterUniqueTogether(
            name='gymmemberfieldschema',
            unique_together={('gym', 'field_key')},
        ),
    ]
