# Generated by Django 6.0.1 on 2026-02-13 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gymattendance_and_more'),
        ('owners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymmember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='gymmember',
            name='phone',
        ),
        migrations.AddField(
            model_name='gymmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to='owners.owner'),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='membership_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='user',
            field=models.OneToOneField(default=1, help_text='The global identity associated with this gym membership.', on_delete=django.db.models.deletion.CASCADE, related_name='gym_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='gymattendance',
            index=models.Index(fields=['gym', 'member', 'date'], name='core_gymatt_gym_id_bc7fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='gymmember',
            index=models.Index(fields=['membership_end'], name='core_gymmem_members_40420c_idx'),
        ),
    ]
