# Generated by Django 6.0.1 on 2026-03-22 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_period', models.PositiveIntegerField(help_text='Duration of the plan in days')),
                ('description', models.CharField(max_length=250)),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALFYEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='core.gym')),
            ],
        ),
        migrations.AddField(
            model_name='gymmember',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gymsubscription'),
        ),
        migrations.AddIndex(
            model_name='gymsubscription',
            index=models.Index(fields=['gym', 'plan_type'], name='core_gymsub_gym_id_33db14_idx'),
        ),
    ]
