# Generated by Django 6.0.1 on 2026-03-22 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_subcription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_subcription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='plan_subcription',
            index=models.Index(fields=['is_active'], name='Plan_plan_s_is_acti_97b2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='plan_subcription',
            index=models.Index(fields=['expiry_date'], name='Plan_plan_s_expiry__7c9982_idx'),
        ),
    ]
