# Generated by Django 6.0.1 on 2026-03-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_config',
            name='tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], max_length=20, unique=True),
        ),
    ]
